### ISSUE TITLE
[TRAVAUX] 1.3.5 Panneau "détail des travaux" (right-panel)

### ISSUE THREAD

**Issue by Agath21** [jdev-org/cartes-dynamiques#25]
## Description 
L’évolution concerne l’affichage des informations des travaux lors du clic sur la carte : 
![image](https://github.com/jdev-org/cartes-dynamiques/assets/22764056/eddc2cf4-b926-4000-8acb-693e2a8f35e4)

Il est demandé les modifications suivantes : 

- supprimer dans l'adresse de chaque résultat, la valeur "ARRONDISSEMENT" qui se trouve toujours en fin de chaine, pour éviter les retours à la ligne.
- Nature du réseau : libeller en toute lettre les valeurs, avec "EP" qui devient "EAU POTABLE", ENP qui devient "EAU NON POTABLE".
- Motif des travaux : remplacer les valeurs actuelles par les termes vulgarisés correspondant dont la liste sera fournie très prochainement.
- Remplacer "Période des travaux prévue" par "Période prévue" pour éviter le retour à la ligne actuel dans le tableau.
- Optimisation de l'affichage du panneau : 

```
#right-panel .panel-body { padding: 5px!important; }
#right-panel .list-group-item { padding: 10px 10px!important; }
.detailArret {padding: 10px!important;margin: 10px 0 0 0!important;}
.detailArret table {margin-top: 5px;}
.adresseArret i { margin-right: 5px; }
.detailArret tr>th:first-child { width: 130px; }
.detailArret tr>td:last-child {color:#FF647D;font-weight:500;} ??
.xs ul.carousel-inner { padding-left: 0px; }
.xs .modal-body .panel-heading { padding: 10px 10px!important; }
```

- Au survol de l'adresse des travaux, une info-bulle informera le cas échéant si les branchements impactés demeurent alimentés en cas d'arrêt d'eau pendant les travaux – texte à préciser par le CiX  Rajout d’un champ booléen : Branchement alimenté (Oui/Non) 

## Spécifications
Attention, il est important de noter qu’avec ce nouveau système, l’interrogation multiple n’est plus possible. Autrement dit, il ne sera pas possible d’afficher les fiches d’informations des travaux lors d’un clic sur un cluster. L’utilisateur devra cliquer sur un cluster, cliquer ensuite sur une zone de travaux pour consulter la fiche associée. 

## Développements
Plusieurs améliorations sont souhaitées et seront réalisés dans le template .mst :

- [ ] Optimiser l'affichage du panneau dans la balise <style> du template en respectant les propriétés de style proposées
- [ ] Modifier le label des certains champs Période
- [ ] Vulgariser les labels des catégories Nature du réseau et motifs des travaux (liste fournies par EDP)
- [ ] Supprimer la valeur « ARRONDISSEMENT » dans l’adresse

## Tests à réaliser
- [ ] Affichage dekstop
- [ ] Affichage mobile

**Comment by Agath21** [comment]
Version de la maquette : 


![Image](https://github.com/jdev-org/cartes-dynamiques/assets/22764056/b4f717db-6d8d-4284-b978-01c511c5c2bf)

**Comment by Agath21** [comment]
RAF : Modifier le label de motif des travaux (en attente de la liste EDP)

**Comment by Gaetanbrl** [comment]
> RAF : Modifier le label de motif des travaux (en attente de la liste EDP)

Pour les travaux,
Les différents labels seront à modifier dans le fichier i18n localisé dans ce répertoire (adapter l'URL selon la branche) : 

https://github.com/jdev-org/cartes-dynamiques/tree/develop/edp_arret_eau

**Comment by Gaetanbrl** [comment]
> > RAF : Modifier le label de motif des travaux (en attente de la liste EDP)
> 
> Pour les travaux, Les différents labels seront à modifier dans le fichier i18n localisé dans ce répertoire (adapter l'URL selon la branche) :
> 
> https://github.com/jdev-org/cartes-dynamiques/tree/develop/edp_arret_eau

Le fonctionnement est "semi-auto". Chaque bouton de filtre a un champ i18n construit à partir de la valeur du champ (les espaces sont remplacés par des `_`).

Exemple :

Si la valeur est `branchement 1` il faudra rajouter dans l'i18n : `edpep.filters.btncheck.branchement_1`
