### ISSUE TITLE
[DASHBOARD] Création d'un tableau de bord pour le suivi des cartes dynamiques

### ISSUE THREAD

**Issue by Agath21** [jdev-org/cartes-dynamiques#27]
En tant que Editeur, vous avez accès aux données de fréquentation de chaque site. Il est demandé de mettre à disposition pour chaque carte dynamique, d’un tableau de bord de suivi des statistiques donnant de la visibilité sur la fréquentation de ces cartes :
•	Courbes de fréquentation des Cartes – permettant de savoir les jours et heures d’affluence par exemple
•	Courbe d’évolution des utilisateurs ou connexions
•	Les fonctionnalités les plus utilisées si possible
•	Etc.

**Comment by pierrejego** [comment]
La solution proposée par Eau de Paris lors de l'émission du besoin ( Google Analytics ) ne répond pas aux contraintes de la CNIL.

La mise en place d'un serveur MATOMO est en cours d'analyse.
