### ISSUE TITLE
[ COMMUN ] Ajouter une configuration par défaut d'impression

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/cartes-dynamiques#29]
Ajouter la configuration sur toutes les cartes en mode desktop.

Juste ajouter le logo EDP quelque part.

**Comment by Agath21** [comment]
Retours à corriger :

- [ ] Portrait par défaut
- [ ] Agrandir le titre de la carte et le logo Eau de Paris 
- [ ] Lors de l'impression passer le titre en bleu EDP
