### ISSUE TITLE
[Commun] - Revoir la fenêtre de partage de la carte

### ISSUE THREAD

**Issue by Gaetanbrl** [jdev-org/cartes-dynamiques#63]
## Demande

Suite à un nouveau besoin, il est demandé de revoir la fenêtre de partage dans une évolution future (version ultérieure après Mise en Production des fontaines).

**Comment by Agath21** [comment]
![Image](https://github.com/jdev-org/cartes-dynamiques/assets/22764056/a7741bbd-b461-44e6-a872-163d1bf39604)

**Comment by Agath21** [comment]
Développement à réaliser : 

- [ ] Mise en place d'un nouveau plugin 
- [ ] Création d'un btn dans la #toolstoolbar permettant d'ouvrir une modal
- [ ] Création d'une nouvelle modal "Partager cette carte"
- [ ] Mise en place de l'IHM avec les boutons 
- [ ] Ajouts des différents liens de partage selon le bouton
